'use client';

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface MemberCostData {
    memberName: string;
    totalMeals: number;
    mealRate: number;
    mealCost: number;
    bazaarSpent: number;
    deposits: number;
    fixedCostShare: number;
    individualCosts: number;
    balance: number;
}

interface CycleMeta {
    messName: string;
    cycleName: string;
    startDate: string;
    endDate: string;
}

// ── Brand Colors ────────────────────────────────────────────────────────────
const CORAL: [number, number, number] = [231, 76, 60];      // #E74C3C
const CORAL_LIGHT: [number, number, number] = [241, 148, 138]; // #F1948A
const DARK: [number, number, number] = [44, 62, 80];         // #2C3E50
const MEDIUM: [number, number, number] = [127, 140, 141];    // #7F8C8D
const LIGHT_BG: [number, number, number] = [253, 237, 236];  // #FDEDEC
const WHITE: [number, number, number] = [255, 255, 255];
const TABLE_HEADER_BG: [number, number, number] = [231, 76, 60];
const TABLE_ALT_ROW: [number, number, number] = [253, 245, 244];

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function getFinalY(doc: any, fallback: number): number {
    return doc.lastAutoTable?.finalY ?? fallback;
}

// ── Draw diagonal watermark ────────────────────────────────────────────────
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function drawWatermark(doc: any) {
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    doc.saveGraphicsState();
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    doc.setGState(new (doc as any).GState({ opacity: 0.06 }));
    doc.setFontSize(60);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...MEDIUM);

    // Rotate text diagonally across the page
    const cx = pageWidth / 2;
    const cy = pageHeight / 2;
    const angle = -35;

    // Draw watermark text
    doc.text('Mess Manager', cx, cy - 30, {
        align: 'center',
        angle,
    });
    doc.text('Mess Manager', cx, cy + 50, {
        align: 'center',
        angle,
    });

    doc.restoreGraphicsState();
}

// ── Draw premium header ────────────────────────────────────────────────────
function drawHeader(doc: jsPDF, title: string, subtitle: string) {
    const pageWidth = doc.internal.pageSize.getWidth();

    // Main title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...CORAL);
    doc.text('Mess Manager: Find Meal Expense Easily', pageWidth / 2, 22, { align: 'center' });

    // Subtitle section
    doc.setFontSize(15);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...CORAL);
    doc.text(title, pageWidth / 2, 36, { align: 'center' });

    // Month title
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...CORAL_LIGHT);
    doc.text(subtitle, pageWidth / 2, 46, { align: 'center' });

    // Thin coral line separator
    doc.setDrawColor(...CORAL_LIGHT);
    doc.setLineWidth(0.5);
    doc.line(20, 50, pageWidth - 20, 50);
}

// ── Draw footer on all pages ───────────────────────────────────────────────
function drawFooter(doc: jsPDF) {
    const totalPages = doc.getNumberOfPages();
    const pageWidth = doc.internal.pageSize.getWidth();

    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        const pageHeight = doc.internal.pageSize.getHeight();

        // Thin line
        doc.setDrawColor(...CORAL_LIGHT);
        doc.setLineWidth(0.3);
        doc.line(14, pageHeight - 16, pageWidth - 14, pageHeight - 16);

        doc.setFontSize(8);
        doc.setTextColor(...MEDIUM);
        doc.text(
            `Generated by Mess Manager (KANGAL) · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
            14, pageHeight - 10
        );
        doc.text(`Page ${i} of ${totalPages}`, pageWidth - 14, pageHeight - 10, { align: 'right' });
    }
}

// ── Info row helper ────────────────────────────────────────────────────────
function drawInfoRows(
    doc: jsPDF,
    startY: number,
    rows: Array<{ label: string; value: string; unit?: string }>
): number {
    let y = startY;
    doc.setFontSize(10);

    for (const row of rows) {
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...DARK);
        doc.text(`${row.label}: `, 20, y);

        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        const labelWidth = doc.getTextWidth(`${row.label}: `);
        doc.text(`${row.value}${row.unit ? ` ${row.unit}` : ''}`, 20 + labelWidth, y);

        y += 7;
    }

    return y;
}

// ── Section heading ────────────────────────────────────────────────────────
function drawSectionHeading(doc: jsPDF, text: string, y: number): number {
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...CORAL);
    doc.text(text, 20, y);

    // Underline
    const textWidth = doc.getTextWidth(text);
    doc.setDrawColor(...CORAL_LIGHT);
    doc.setLineWidth(0.4);
    doc.line(20, y + 1.5, 20 + textWidth, y + 1.5);

    return y + 8;
}

// ============================================================================
// ALL MEMBERS REPORT (Matches Screenshot Style)
// ============================================================================

export function exportAllMembersPDF(
    members: MemberCostData[],
    cycle: CycleMeta,
    fixedCosts: Array<{ type: string; amount: number }>,
    totalBazaar: number,
    totalDeposits: number
) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Watermark
    drawWatermark(doc);

    // Header
    drawHeader(doc, 'Active Month Details', `Month Title: ${cycle.cycleName}`);

    // ── Mess Summary Info ──────────────────────────────────────────────────
    const totalMeals = members.reduce((s, m) => s + m.totalMeals, 0);
    const mealRate = members.length > 0 ? members[0].mealRate : 0;
    const totalMealCost = members.reduce((s, m) => s + m.mealCost, 0);
    const totalFixedCost = fixedCosts.reduce((s, c) => s + c.amount, 0);
    const totalIndividualCost = members.reduce((s, m) => s + m.individualCosts, 0);
    const messTotalCost = totalMealCost + totalFixedCost + totalIndividualCost;
    const messBalance = totalDeposits - messTotalCost;

    let y = 58;
    y = drawInfoRows(doc, y, [
        { label: 'Mess Name', value: cycle.messName },
        { label: 'Mess Balance', value: messBalance.toFixed(2), unit: '৳' },
        { label: 'Mess Total Meal', value: totalMeals.toFixed(2) },
        { label: 'Mess Total Deposit', value: totalDeposits.toFixed(2), unit: '৳' },
        { label: 'Mess Total Meal Cost', value: totalMealCost.toFixed(2), unit: '৳৳' },
        { label: 'Mess Meal Rate', value: mealRate.toFixed(2), unit: '৳৳' },
        { label: 'Total Shared Cost', value: totalFixedCost.toFixed(2), unit: '৳৳' },
        { label: 'Total Individual Cost', value: totalIndividualCost.toFixed(2), unit: '৳৳' },
        { label: 'Mess Total Cost(Meal+Other)', value: messTotalCost.toFixed(2), unit: '৳' },
    ]);

    y += 6;

    // ── Member Summary Table ───────────────────────────────────────────────
    y = drawSectionHeading(doc, 'Member Summary Info Table', y);

    autoTable(doc as unknown as jsPDF, {
        startY: y,
        head: [['Member Name', 'Total Meal', 'Total Deposit', 'Total Cost(Meal+Shared+Individual)', 'Balance']],
        body: members.map(m => {
            const totalCost = m.mealCost + m.fixedCostShare + m.individualCosts;
            return [
                m.memberName,
                m.totalMeals.toFixed(1),
                m.deposits.toFixed(2),
                totalCost.toFixed(2),
                m.balance.toFixed(2),
            ];
        }),
        theme: 'grid',
        headStyles: {
            fillColor: TABLE_HEADER_BG,
            textColor: WHITE,
            fontSize: 9,
            fontStyle: 'bold',
            halign: 'center',
            cellPadding: 4,
        },
        bodyStyles: {
            fontSize: 9,
            textColor: DARK,
            cellPadding: 3.5,
        },
        alternateRowStyles: {
            fillColor: TABLE_ALT_ROW,
        },
        columnStyles: {
            0: { cellWidth: 38, fontStyle: 'bold' },
            1: { halign: 'center', cellWidth: 25 },
            2: { halign: 'center', cellWidth: 30 },
            3: { halign: 'center' },
            4: { halign: 'center', cellWidth: 25 },
        },
        styles: {
            lineColor: [220, 220, 220],
            lineWidth: 0.3,
        },
        margin: { left: 14, right: 14 },
    });

    y = getFinalY(doc, y + 40);

    // ── Fixed Costs Breakdown ──────────────────────────────────────────────
    if (fixedCosts.length > 0) {
        // Check if we need a new page
        if (y > doc.internal.pageSize.getHeight() - 80) {
            doc.addPage();
            drawWatermark(doc);
            y = 20;
        }

        y += 10;
        y = drawSectionHeading(doc, 'Shared/Fixed Costs Breakdown', y);

        autoTable(doc as unknown as jsPDF, {
            startY: y,
            head: [['Cost Type', 'Amount (৳)']],
            body: fixedCosts.map(c => [
                c.type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
                c.amount.toFixed(2),
            ]),
            theme: 'grid',
            headStyles: {
                fillColor: TABLE_HEADER_BG,
                textColor: WHITE,
                fontSize: 9,
                fontStyle: 'bold',
                cellPadding: 4,
            },
            bodyStyles: {
                fontSize: 9,
                textColor: DARK,
                cellPadding: 3,
            },
            alternateRowStyles: {
                fillColor: TABLE_ALT_ROW,
            },
            columnStyles: {
                1: { halign: 'right', fontStyle: 'bold' },
            },
            styles: {
                lineColor: [220, 220, 220],
                lineWidth: 0.3,
            },
            tableWidth: 120,
            margin: { left: 14 },
        });

        y = getFinalY(doc, y + 30);
    }

    // ── Per-Member Detailed Breakdown ──────────────────────────────────────
    if (y > doc.internal.pageSize.getHeight() - 80) {
        doc.addPage();
        drawWatermark(doc);
        y = 20;
    }

    y += 10;
    y = drawSectionHeading(doc, 'Per-Member Detailed Breakdown', y);

    autoTable(doc as unknown as jsPDF, {
        startY: y,
        head: [['Member', 'Meals', 'Rate', 'Meal Cost', 'Shared', 'Individual', 'Deposit', 'Bazaar', 'Balance']],
        body: members.map(m => [
            m.memberName,
            m.totalMeals.toFixed(1),
            `৳${m.mealRate.toFixed(2)}`,
            `৳${m.mealCost.toFixed(2)}`,
            `৳${m.fixedCostShare.toFixed(2)}`,
            `৳${m.individualCosts.toFixed(2)}`,
            `৳${m.deposits.toFixed(2)}`,
            `৳${m.bazaarSpent.toFixed(2)}`,
            `৳${m.balance.toFixed(2)}`,
        ]),
        theme: 'grid',
        headStyles: {
            fillColor: TABLE_HEADER_BG,
            textColor: WHITE,
            fontSize: 7.5,
            fontStyle: 'bold',
            halign: 'center',
            cellPadding: 3,
        },
        bodyStyles: {
            fontSize: 7.5,
            textColor: DARK,
            cellPadding: 2.5,
        },
        alternateRowStyles: {
            fillColor: TABLE_ALT_ROW,
        },
        columnStyles: {
            0: { cellWidth: 30, fontStyle: 'bold' },
            8: { fontStyle: 'bold' },
        },
        styles: {
            lineColor: [220, 220, 220],
            lineWidth: 0.3,
        },
        margin: { left: 10, right: 10 },
    });

    // Footer
    drawFooter(doc);

    doc.save(`All_Members_Report_${cycle.cycleName.replace(/\s+/g, '_')}.pdf`);
}

// ============================================================================
// SINGLE MEMBER REPORT
// ============================================================================

export function exportSingleMemberPDF(
    member: MemberCostData,
    cycle: CycleMeta,
    deposits: Array<{ date: string; amount: number; method: string }>,
    bazaarTrips: Array<{ date: string; amount: number; items: string }>,
    individualCosts: Array<{ description: string; amount: number; status: string }>
) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Watermark
    drawWatermark(doc);

    // Header
    drawHeader(doc, 'Member Report', `${member.memberName} · ${cycle.cycleName}`);

    // ── Member Summary ─────────────────────────────────────────────────────
    let y = 58;
    y = drawInfoRows(doc, y, [
        { label: 'Mess Name', value: cycle.messName },
        { label: 'Member Name', value: member.memberName },
        { label: 'Cycle', value: `${cycle.cycleName} (${cycle.startDate} — ${cycle.endDate})` },
    ]);

    y += 4;

    // Summary table
    y = drawSectionHeading(doc, 'Financial Summary', y);

    autoTable(doc as unknown as jsPDF, {
        startY: y,
        head: [['Item', 'Value']],
        body: [
            ['Total Meals', member.totalMeals.toFixed(1)],
            ['Meal Rate', `৳ ${member.mealRate.toFixed(2)}`],
            ['Meal Cost', `৳ ${member.mealCost.toFixed(2)}`],
            ['Shared/Fixed Cost Share', `৳ ${member.fixedCostShare.toFixed(2)}`],
            ['Individual Costs', `৳ ${member.individualCosts.toFixed(2)}`],
            ['Total Deposits', `৳ ${member.deposits.toFixed(2)}`],
            ['Bazaar Shopping', `৳ ${member.bazaarSpent.toFixed(2)}`],
            ['Balance', `৳ ${member.balance.toFixed(2)}`],
        ],
        theme: 'grid',
        headStyles: {
            fillColor: TABLE_HEADER_BG,
            textColor: WHITE,
            fontSize: 10,
            fontStyle: 'bold',
            cellPadding: 4,
        },
        bodyStyles: {
            fontSize: 10,
            textColor: DARK,
            cellPadding: 3.5,
        },
        alternateRowStyles: {
            fillColor: TABLE_ALT_ROW,
        },
        columnStyles: {
            1: { halign: 'right', fontStyle: 'bold' },
        },
        styles: {
            lineColor: [220, 220, 220],
            lineWidth: 0.3,
        },
        margin: { left: 20, right: 20 },
    });

    y = getFinalY(doc, 160);

    // ── Deposits ───────────────────────────────────────────────────────────
    if (deposits.length > 0) {
        if (y > doc.internal.pageSize.getHeight() - 60) {
            doc.addPage();
            drawWatermark(doc);
            y = 20;
        }
        y += 10;
        y = drawSectionHeading(doc, 'Deposit History', y);

        autoTable(doc as unknown as jsPDF, {
            startY: y,
            head: [['Date', 'Amount (৳)', 'Method']],
            body: deposits.map(d => [d.date, d.amount.toFixed(2), d.method]),
            theme: 'grid',
            headStyles: {
                fillColor: TABLE_HEADER_BG,
                textColor: WHITE,
                fontSize: 9,
                fontStyle: 'bold',
                cellPadding: 3,
            },
            bodyStyles: {
                fontSize: 9,
                textColor: DARK,
                cellPadding: 3,
            },
            alternateRowStyles: { fillColor: TABLE_ALT_ROW },
            columnStyles: { 1: { halign: 'right' } },
            styles: { lineColor: [220, 220, 220], lineWidth: 0.3 },
            margin: { left: 20, right: 20 },
        });
        y = getFinalY(doc, y + 30);
    }

    // ── Bazaar Trips ───────────────────────────────────────────────────────
    if (bazaarTrips.length > 0) {
        if (y > doc.internal.pageSize.getHeight() - 60) {
            doc.addPage();
            drawWatermark(doc);
            y = 20;
        }
        y += 10;
        y = drawSectionHeading(doc, 'Bazaar Shopping Trips', y);

        autoTable(doc as unknown as jsPDF, {
            startY: y,
            head: [['Date', 'Amount (৳)', 'Items']],
            body: bazaarTrips.map(b => [b.date, b.amount.toFixed(2), b.items]),
            theme: 'grid',
            headStyles: {
                fillColor: TABLE_HEADER_BG,
                textColor: WHITE,
                fontSize: 9,
                fontStyle: 'bold',
                cellPadding: 3,
            },
            bodyStyles: {
                fontSize: 9,
                textColor: DARK,
                cellPadding: 3,
            },
            alternateRowStyles: { fillColor: TABLE_ALT_ROW },
            columnStyles: { 1: { halign: 'right' } },
            styles: { lineColor: [220, 220, 220], lineWidth: 0.3 },
            margin: { left: 20, right: 20 },
        });
        y = getFinalY(doc, y + 30);
    }

    // ── Individual Costs ───────────────────────────────────────────────────
    if (individualCosts.length > 0) {
        if (y > doc.internal.pageSize.getHeight() - 60) {
            doc.addPage();
            drawWatermark(doc);
            y = 20;
        }
        y += 10;
        y = drawSectionHeading(doc, 'Individual Costs', y);

        autoTable(doc as unknown as jsPDF, {
            startY: y,
            head: [['Description', 'Amount (৳)', 'Status']],
            body: individualCosts.map(c => [c.description, c.amount.toFixed(2), c.status]),
            theme: 'grid',
            headStyles: {
                fillColor: TABLE_HEADER_BG,
                textColor: WHITE,
                fontSize: 9,
                fontStyle: 'bold',
                cellPadding: 3,
            },
            bodyStyles: {
                fontSize: 9,
                textColor: DARK,
                cellPadding: 3,
            },
            alternateRowStyles: { fillColor: TABLE_ALT_ROW },
            columnStyles: { 1: { halign: 'right' } },
            styles: { lineColor: [220, 220, 220], lineWidth: 0.3 },
            margin: { left: 20, right: 20 },
        });
    }

    // Footer
    drawFooter(doc);

    doc.save(`${member.memberName.replace(/\s+/g, '_')}_report_${cycle.cycleName.replace(/\s+/g, '_')}.pdf`);
}
